name: 'Terraform Apply on push'
on:
  push:
  pull_request:
env:
  tf_version: '1.1.6'
  tf_actions_working_dir: 'infrastructure/aws'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}

      - name: 'Terraform format'
        id: fmt
        run: terraform fmt -check -diff

      - name: 'Terraform Init'
        id: init
        run: terraform init

      - name: 'Terraform Validate'
        id: validate
        run: terraform validate

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        id: apply
        run: terraform apply -auto-approve
        continue-on-error: true
